NUTRIENTES_REFERENCIA_PERRO = {
    "Proteína":         {"min": 6.25, "max": None, "unit": "g/100g"},
    "EM":               {"min": 1000, "max": None, "unit": "kcal/kg"},
    "Grasa":            {"min": 2.125, "max": None, "unit": "g/100g"},
    "Ácido Linoleico":  {"min": 0.325, "max": 1.625, "unit": "g/100g"},
    "Ca":               {"min": 0.25, "max": 0.4, "unit": "g/100g"},
    "P":                {"min": 0.225, "max": None, "unit": "g/100g"},
    "Na":               {"min": 0.055, "max": None, "unit": "g/100g"},
    "Cl":               {"min": 0.085, "max": None, "unit": "g/100g"},
    "Lisina":           {"min": 0.22, "max": 0.7, "unit": "g/100g"},
    "Metionina":        {"min": 0.088, "max": None, "unit": "g/100g"},
    "Metionina + Cistina": {"min": 0.175, "max": None, "unit": "g/100g"},
    "Valina":           {"min": 0.17, "max": None, "unit": "g/100g"},
    "Triptofano":       {"min": 0.058, "max": None, "unit": "g/100g"},
    "Fenilalanina":     {"min": 0.163, "max": None, "unit": "g/100g"},
    "Isoleucina":       {"min": 0.163, "max": None, "unit": "g/100g"},
    "Treonina":         {"min": 0.203, "max": None, "unit": "g/100g"},
    "Arginina":         {"min": 0.204, "max": None, "unit": "g/100g"},
    "Leucina":          {"min": 0.323, "max": None, "unit": "g/100g"},
    "Ca:P (relación)":  {"min": "1/1", "max": "1.6/1", "unit": "-"},
    "Vitamina A":       {"min": 1250, "max": None, "unit": "mil UI/kg"},
    "Vitamina D3":      {"min": 138, "max": None, "unit": "mil UI/kg"},
    "Vitamina E2":      {"min": 12.5, "max": None, "unit": "mg/kg"},
    "Vitamina K3":      {"min": None, "max": None, "unit": "mg/kg"},
    "Tiamina - B1":     {"min": 0.45, "max": None, "unit": "mg/kg"},
    "Riboflavina - B2": {"min": 1.05, "max": None, "unit": "mg/kg"},
    "Piridoxina - B6":  {"min": 0.38, "max": None, "unit": "mg/kg"},
    "Cobalamina - B12": {"min": 7, "max": None, "unit": "µg/kg"},
    "Ácido fólico":     {"min": 54, "max": None, "unit": "µg/kg"},
    "Niacina":          {"min": 3.4, "max": None, "unit": "mg/kg"},
    "Ácido pantoténico": {"min": 3, "max": None, "unit": "mg/kg"},
    "Biotina":          {"min": 10, "max": None, "unit": "mg/kg"},
    "Colina total":     {"min": 425, "max": None, "unit": "mg/kg"},
    "Hierro":           {"min": 22, "max": None, "unit": "mg/kg"},
    "Cobre":            {"min": 2.75, "max": None, "unit": "mg/kg"},
    "Zinc":             {"min": 25, "max": None, "unit": "mg/kg"},
    "Manganeso":        {"min": 1.4, "max": None, "unit": "mg/kg"},
    "Selenio":          {"min": 100, "max": None, "unit": "mg/kg"},
    "Yodo":             {"min": 0.38, "max": None, "unit": "mg/kg"},
}

NUTRIENTES_REFERENCIA_GATO = {
    "proteína": 60,
    "calcio": 1.2,
    "fósforo": 1.0,
    # ... agrega más nutrientes
}
