NUTRIENTES_REFERENCIA_PERRO = {
    "Proteína":         {"min": 62.5, "max": None, "unit": "g"},
    "Energía Metabolizable (kcal/kg)": {"min": 1000, "max": None, "unit": "kcal/kg"},
    "Energía Metabolizable (kcal/g)": {"min": 100, "max": None, "unit": "kcal/g"},
    "Grasa":            {"min": 21.25, "max": None, "unit": "g"},
    "Ácido Linoleico":  {"min": 3.25, "max": 16.25, "unit": "g"},
    "Calcio - Ca":      {"min": 2.5, "max": 4, "unit": "g"},
    "Fósforo - P":      {"min": 2.25, "max": None, "unit": "g"},
    "Sodio - Na":       {"min": 0.55, "max": None, "unit": "g"},
    "Cloro - Cl":       {"min": 0.85, "max": None, "unit": "g"},
    "Lisina":           {"min": 2.2, "max": 7, "unit": "g"},
    "Metionina":        {"min": 0.88, "max": None, "unit": "g"},
    "Metionina + Cistina": {"min": 1.75, "max": None, "unit": "g"},
    "Valina":           {"min": 1.7, "max": None, "unit": "g"},
    "Triptofano":       {"min": 0.58, "max": None, "unit": "g"},
    "Fenilalanina":     {"min": 1.63, "max": None, "unit": "g"},
    "Isoleucina":       {"min": 1.63, "max": None, "unit": "g"},
    "Treonina":         {"min": 2.03, "max": None, "unit": "g"},
    "Arginina":         {"min": 2.04, "max": None, "unit": "g"},
    "Leucina":          {"min": 3.23, "max": None, "unit": "g"},
    "Ca:P (relación)":  {"min": "1/1", "max": "1.6/1", "unit": "-"},
    "Vitamina A":       {"min": 1250, "max": None, "unit": "mil UI/kg"},
    "Vitamina D3":      {"min": 138, "max": None, "unit": "mil UI/kg"},
    "Vitamina E2":      {"min": 12.5, "max": None, "unit": "mg/kg"},
    "Vitamina K3":      {"min": None, "max": None, "unit": "mg/kg"},
    "Tiamina - B1":     {"min": 0.45, "max": None, "unit": "mg/kg"},
    "Riboflavina - B2": {"min": 1.05, "max": None, "unit": "mg/kg"},
    "Piridoxina - B6":  {"min": 0.38, "max": None, "unit": "mg/kg"},
    "Cobalamina - B12": {"min": 7, "max": None, "unit": "µg/kg"},
    "Ácido fólico":     {"min": 54, "max": None, "unit": "µg/kg"},
    "Niacina":          {"min": 3.4, "max": None, "unit": "mg/kg"},
    "Ácido pantoténico": {"min": 3, "max": None, "unit": "mg/kg"},
    "Biotina":          {"min": 10, "max": None, "unit": "mg/kg"},
    "Colina total":     {"min": 425, "max": None, "unit": "mg/kg"},
    "Hierro":           {"min": 22, "max": None, "unit": "mg/kg"},
    "Cobre":            {"min": 2.75, "max": None, "unit": "mg/kg"},
    "Zinc":             {"min": 25, "max": None, "unit": "mg/kg"},
    "Manganeso":        {"min": 1.4, "max": None, "unit": "mg/kg"},
    "Selenio":          {"min": 100, "max": None, "unit": "mg/kg"},
    "Yodo":             {"min": 0.38, "max": None, "unit": "mg/kg"},
}
NUTRIENTES_REFERENCIA_GATO = {
    "proteína": 60,
    "calcio": 1.2,
    "fósforo": 1.0,
    # ... agrega más nutrientes
}
